showNotBar: true
barBody: "ANNOUNCEMENT: We're now SOC 2 Type II
  certified.[](https://fingerprint.com/blog/soc-2-type-2/)"
arrowText: Read more
url: /blog/soc-2-type-2/
openUrlNewTab: false
backgroundColor: "#f04405"
